# TensorFlow Introduction

A tensor is an algebraic object that describes a (multilinear) relationship between sets of algebraic objects related to a vector space. Objects that tensors may map between include vectors and scalars, and even other tensors. Tensors are immutable - cannot update them, only create a new one. Examples of using Tensors in tensorflow:
- Basic Tensors - different ranks
- Tensor shapes
- Tensor Indexing
- Resphaping Tensors

In [1]:
# importing packages
import tensorflow as tf
import numpy as np

In [2]:
# checking version
tf.__version__

'2.1.0'

# Basic Tensors

### Zero rank tensor (constant)

In [3]:
# data type is int32
rankZero = tf.constant(10)
rankZero

<tf.Tensor: shape=(), dtype=int32, numpy=10>

### Rank 1 tensor (vector)

In [4]:
# data type is float32
rankOne = tf.constant([0.0, 1.0, 1.0, 2.0, 3.0, 5.0, 8.0, 13.0, 21.0, 34.0])
print(rankOne)
rankOne

tf.Tensor([ 0.  1.  1.  2.  3.  5.  8. 13. 21. 34.], shape=(10,), dtype=float32)


<tf.Tensor: shape=(10,), dtype=float32, numpy=array([ 0.,  1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34.], dtype=float32)>

### Rank 2 tensor (matrix) - has 2 axes

In [5]:
# data type is float64
rankTwo = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float64)
print(rankTwo)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float64)


### Tensor with 3 axes (dimensions)

In [6]:
# data type is int32
rankThree = tf.constant([
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],
  [[30, 31, 32, 33, 34],
   [35, 36, 37, 38, 39]],])
print(rankThree)

tf.Tensor(
[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]], shape=(3, 2, 5), dtype=int32)


### Convert Tensor to NumPy array 

In [7]:
# converting a tensor to a numpy array
rankThree.numpy()

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]], dtype=int32)

In [8]:
# converting tensor to a numpy array
a = np.array(rankThree)
print(type(a))

<class 'numpy.ndarray'>


In [9]:
a

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]], dtype=int32)

# tf.Tensor

**tf.Tensor** class used in many datasets requires the tensors to be rectangular - along each axis, every element is the same size. **tf.Tensor** supports addition, element-wise multiplication and matrix multiplication.

In [10]:
# creating a tensor
x = tf.constant([[1, 2], [3, 4]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [11]:
# creating a tensor
y = tf.constant([[2, 3], [2, 3]])
y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [2, 3]], dtype=int32)>

In [12]:
# printing calculations
print(tf.add(x, y), "\n")
print(tf.multiply(x, y), "\n")
print(tf.matmul(x, y), "\n")

tf.Tensor(
[[3 5]
 [5 7]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 2  6]
 [ 6 12]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[ 6  9]
 [14 21]], shape=(2, 2), dtype=int32) 



In [13]:
# assigning values to a tensor
z = tf.constant([[4.0, 5.0], [10.0, 1.0]])
print(z)

tf.Tensor(
[[ 4.  5.]
 [10.  1.]], shape=(2, 2), dtype=float32)


In [14]:
# finding the index of max value
print(tf.argmax(z))

tf.Tensor([1 0], shape=(2,), dtype=int64)


In [15]:
# finding the largest value
print(tf.reduce_max(z))

tf.Tensor(10.0, shape=(), dtype=float32)


# Tensor Shapes

- **Shape:** The length (number of elements) of each of the dimensions of a tensor.
- **Rank:** Number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
- **Dimension or Axis:** A particular dimension of a tensor.
- **Size:** The total number of items in the tensor, the product shape vector.

Tensors and **tf.TensorShape** provide useful properties for accessing information


In [16]:
# 4 dimension tensor initialized to zeros
rankFour = tf.zeros([3, 2, 4, 5])

In [17]:
print("Type of every element:", rankFour.dtype)
print("Number of dimensions:", rankFour.ndim)
print("Shape of tensor:", rankFour.shape)
print("Elements along axis 0 of tensor:", rankFour.shape[0])
print("Elements along the last axis of tensor:", rankFour.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rankFour))
print("Total number of elements (3*2*4*5): ", tf.size(rankFour).numpy())

Type of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements (3*2*4*5):  120


# Tensor Indexing

- Zero based indexing
- Can use negative indexing (counts backwards), starts with -1
- Just like python list use colons *start:stop:step*.

### Single dimension indexing

In [18]:
print(rankOne.numpy())

[ 0.  1.  1.  2.  3.  5.  8. 13. 21. 34.]


In [19]:
print("First:", rankOne[0].numpy())
print("Second:", rankOne[1].numpy())
print("Last:", rankOne[-1].numpy())

First: 0.0
Second: 1.0
Last: 34.0


In [20]:
# like python list slicing
print("Everything:", rankOne[:].numpy())
print("Before 4:", rankOne[:4].numpy())
print("From 4 to the end:", rankOne[4:].numpy())
print("From 2, before 7:", rankOne[2:7].numpy())
print("Every other item:", rankOne[::2].numpy())
print("Reversed:", rankOne[::-1].numpy())

Everything: [ 0.  1.  1.  2.  3.  5.  8. 13. 21. 34.]
Before 4: [0. 1. 1. 2.]
From 4 to the end: [ 3.  5.  8. 13. 21. 34.]
From 2, before 7: [1. 2. 3. 5. 8.]
Every other item: [ 0.  1.  3.  8. 21.]
Reversed: [34. 21. 13.  8.  5.  3.  2.  1.  1.  0.]


### Multi dimension/axis indexing

In [21]:
print(rankTwo.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [22]:
# getting single value from a 2-rank tensor
print(rankTwo[1, 1].numpy())

4.0


In [23]:
print("Second row:", rankTwo[1, :].numpy())
print("Second column:", rankTwo[:, 1].numpy())
print("Last row:", rankTwo[-1, :].numpy())
print("First item in last column:", rankTwo[0, -1].numpy())
print("Skip the first row:")
print(rankTwo[1:, :].numpy(), "\n")

Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]
 [5. 6.]] 



In [24]:
print(rankThree.numpy())

[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]]


In [25]:
# rankThree is (3 x 2 x 5) tensor and all values at index 4 of the last axis is printed
print(rankThree[:, :, 4])

tf.Tensor(
[[14 19]
 [24 29]
 [34 39]], shape=(3, 2), dtype=int32)


## Manipulating Shape

- Reshaping is very useful especially when handling images, texts data.
- **tf.reshape** is very fast and cheap operation as the data does not need to be duplicated.
- The data maintains its layout in memory and a new tensor is created, with the requested shape, pointing to the same data.

In [26]:
# shape returns a `TensorShape` object that shows the size on each dimension
x = tf.constant([[1], [2], [3]])
print(x.shape)

(3, 1)


In [27]:
# converting this object into a Python list, too
print(x.shape.as_list())

[3, 1]


In [28]:
# reshaping a tensor to a new shape
reshaped = tf.reshape(x, [1, 3])

In [29]:
print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


In [30]:
print(rankThree)

tf.Tensor(
[[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]], shape=(3, 2, 5), dtype=int32)


In [31]:
# `-1` passed in the `shape` argument says "Whatever fits"
print(tf.reshape(rankThree, [-1]))

tf.Tensor(
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39], shape=(30,), dtype=int32)


In [32]:
# reshaping to (3x2)x5
print(tf.reshape(rankThree, [6, 5]), "\n")

tf.Tensor(
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]], shape=(6, 5), dtype=int32) 



In [33]:
# reshaping to 3x(2x5)
print(tf.reshape(rankThree, [3, -1]))

tf.Tensor(
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]], shape=(3, 10), dtype=int32)
